import type { BookChapter } from '../types';

export const vocabulary: BookChapter = {
  id: 'vocabulary',
  title: 'Vocabulary',
  summary: 'The learning system, the roots worth knowing, and 200 high-frequency words grouped by theme.',
  sections: [
    {
      id: 'vocab-system',
      title: 'The learning system',
      blocks: [
        {
          kind: 'p',
          text: 'Flashcards, spaced repetition, 20 new words a day, reviewed daily. Anki is free and does the scheduling for you. Three rules make the difference between memorizing and knowing:',
        },
        {
          kind: 'ol',
          items: [
            '**Learn the word in a sentence, not as a definition pair.** "Laconic = using few words" is fragile. "His laconic reply, a single word, ended the conversation" sticks.',
            '**Tag each word’s charge:** positive, negative, or neutral. On test day, half the questions are solvable on charge alone. If you know *obsequious* is negative and the sentence needs a compliment, you are done.',
            '**Review the words you know, not just the ones you do not.** The whole point of spaced repetition is catching words at the edge of forgetting.',
          ],
        },
      ],
    },
    {
      id: 'roots',
      title: 'Roots worth knowing',
      blocks: [
        {
          kind: 'p',
          text: 'Roots will not give you precise definitions, but they reliably give you charge and rough direction, which is often enough.',
        },
        {
          kind: 'table',
          head: ['Root', 'Meaning', 'Examples'],
          rows: [
            ['a-, an-', 'without', 'amoral, anomalous, atypical, apathy'],
            ['ambi-, amphi-', 'both', 'ambiguous, ambivalent, amphibious'],
            ['bene-, bon-', 'good', 'benevolent, benign, bonhomie'],
            ['circum-', 'around', 'circumscribe, circumspect, circumvent'],
            ['contra-, counter-', 'against', 'contravene, countermand, contradict'],
            ['dis-, dif-', 'apart, not', 'dissent, disparate, diffident'],
            ['eu-', 'good, well', 'eulogy, euphemism, euphony'],
            ['ex-, e-', 'out', 'extol, expunge, ebullient, eloquent'],
            ['in-, im-', 'not, or into', 'inept, implacable; but also imbue, infuse'],
            ['loqu-, loc-', 'speak', 'loquacious, grandiloquent, circumlocution'],
            ['mal-, mis-', 'bad', 'malevolent, malinger, misanthrope'],
            ['ob-', 'against', 'obstinate, obdurate, obfuscate'],
            ['pac-, plac-', 'peace, please', 'pacify, placate, implacable, complacent'],
            ['per-', 'through, thoroughly', 'pervade, perfunctory, pertinacious'],
            ['pro-', 'forward, for', 'prodigal, propitiate, proponent'],
            ['son-, phon-', 'sound', 'sonorous, dissonant, cacophony, euphony'],
            ['spec-, spic-', 'look', 'perspicacious, circumspect, specious'],
            ['taci-, tac-', 'silent', 'taciturn, tacit, reticent'],
            ['ten-, tain-', 'hold', 'tenacious, tenable, abstain, untenable'],
            ['ver-', 'truth', 'veracity, verisimilitude, aver'],
          ],
        },
        {
          kind: 'callout',
          tone: 'warn',
          body: [
            'Note the trap in *in-* and *im-*: it means "not" in *inept* but "into" in *imbue*. Roots are a heuristic, not a rule.',
          ],
        },
      ],
    },
    {
      id: 'word-list',
      title: '200 high-frequency words',
      blocks: [
        {
          kind: 'p',
          text: 'These are the words that recur on the GRE. Learn them in the order of the groups below; the first group is the highest-yield. Where a group is split, the two clusters are opposites.',
        },
        {
          kind: 'words',
          label: 'Group 1: praise and criticism (the GRE’s favorite axis)',
          clusters: [
            {
              items: [
                'laud — praise',
                'extol — praise highly',
                'venerate — revere',
                'exalt — glorify',
                'tout — promote',
                'acclaim',
                'eulogize',
                'panegyric — a formal speech of praise',
                'encomium — high praise',
                'plaudit — expression of approval',
              ],
            },
            {
              items: [
                'censure — formally criticize',
                'excoriate — criticize severely',
                'castigate — rebuke harshly',
                'decry — denounce',
                'deprecate — express disapproval',
                'disparage — belittle',
                'denigrate — defame',
                'vilify — speak abusively of',
                'lambaste — criticize harshly',
                'impugn — call into question',
                'calumny — slander',
                'opprobrium — public disgrace',
                'invective — abusive language',
                'diatribe — a bitter verbal attack',
                'polemic — a strongly critical argument',
              ],
            },
          ],
        },
        {
          kind: 'words',
          label: 'Group 2: speech and silence',
          clusters: [
            {
              items: [
                'laconic — using few words',
                'taciturn — habitually silent',
                'reticent — reluctant to speak',
                'terse — brief, sometimes curtly so',
                'succinct — briefly and clearly expressed',
                'pithy — concise and forceful',
                'concise',
              ],
            },
            {
              items: [
                'loquacious — talkative',
                'garrulous — excessively talkative',
                'voluble — fluent and rapid in speech',
                'verbose — wordy',
                'prolix — tediously lengthy',
                'grandiloquent — pompous in language',
                'bombastic — inflated language',
                'circumlocution — roundabout speech',
                'digression',
              ],
            },
          ],
        },
        {
          kind: 'words',
          label: 'Group 3: agreement and opposition',
          clusters: [
            {
              items: [
                'accede — agree to',
                'acquiesce — accept reluctantly',
                'assent',
                'concur',
                'corroborate — confirm with evidence',
                'substantiate',
                'vindicate — clear from blame; justify',
                'ratify',
              ],
            },
            {
              items: [
                'demur — raise objections',
                'dissent',
                'gainsay — deny, contradict',
                'rebut',
                'refute — disprove',
                'repudiate — reject',
                'recant — withdraw a statement',
                'renounce',
                'contravene — violate, conflict with',
                'belie — contradict or misrepresent',
              ],
            },
          ],
        },
        {
          kind: 'words',
          label: 'Group 4: character — difficult people',
          clusters: [
            {
              items: [
                'obstinate — stubborn',
                'obdurate — unyielding',
                'intransigent — refusing compromise',
                'recalcitrant — resisting authority',
                'intractable — hard to control',
                'contumacious — insubordinate',
              ],
            },
            {
              items: [
                'irascible — easily angered',
                'truculent — aggressively defiant',
                'pugnacious — eager to fight',
                'bellicose — inclined to war',
                'querulous — habitually complaining',
                'petulant — childishly sulky',
                'captious — fond of finding fault',
              ],
            },
            {
              items: [
                'imperious — domineering',
                'haughty',
                'supercilious — contemptuously superior',
                'disdainful',
                'arrogant',
              ],
            },
          ],
        },
        {
          kind: 'words',
          label: 'Group 5: character — agreeable and servile',
          clusters: [
            {
              items: [
                'affable — friendly',
                'amiable',
                'genial',
                'gregarious — sociable',
                'convivial — festive and sociable',
                'magnanimous — generous in spirit',
                'munificent — very generous',
                'altruistic',
                'beneficent',
              ],
            },
            {
              items: [
                'obsequious — excessively obedient',
                'servile',
                'sycophantic — flattering to gain advantage',
                'fawning',
                'unctuous — excessively ingratiating',
                'toady',
              ],
            },
          ],
        },
        {
          kind: 'words',
          label: 'Group 6: honesty and deception',
          clusters: [
            {
              items: [
                'candid — frank',
                'forthright',
                'ingenuous — innocent, unguarded',
                'guileless',
                'veracity — truthfulness',
                'probity — integrity',
                'scrupulous — morally rigorous',
              ],
            },
            {
              items: [
                'disingenuous — pretending ignorance',
                'duplicitous',
                'mendacious — lying',
                'specious — superficially plausible but wrong',
                'sophistry — fallacious reasoning meant to deceive',
                'dissemble — conceal one’s motives',
                'prevaricate — speak evasively',
                'obfuscate — make deliberately unclear',
                'chicanery — trickery',
                'artifice',
                'subterfuge',
                'guile',
                'perfidy — betrayal',
              ],
            },
          ],
        },
        {
          kind: 'words',
          label: 'Group 7: caution, prudence, and their opposites',
          clusters: [
            {
              items: [
                'circumspect — cautious',
                'prudent',
                'judicious — showing good judgment',
                'discreet',
                'wary',
                'chary — cautiously reluctant',
              ],
            },
            {
              items: [
                'temerity — reckless boldness',
                'audacity',
                'effrontery — insolent boldness',
                'foolhardy',
                'rash',
                'impetuous — acting without thought',
                'precipitate — hasty',
                'profligate — recklessly extravagant',
                'prodigal — wastefully extravagant',
              ],
            },
          ],
        },
        {
          kind: 'words',
          label: 'Group 8: certainty, doubt, and indifference',
          clusters: [
            {
              items: [
                'dogmatic — asserting opinions as fact',
                'adamant',
                'resolute',
                'steadfast',
                'staunch',
              ],
            },
            {
              items: [
                'skeptical',
                'dubious',
                'incredulous — unwilling to believe',
                'equivocal — ambiguous',
                'ambivalent — having mixed feelings',
                'tentative',
                'provisional',
                'diffident — lacking confidence',
              ],
            },
            {
              items: [
                'apathetic',
                'indifferent',
                'phlegmatic — unemotionally calm',
                'stoic',
                'impassive',
                'dispassionate — unbiased by emotion',
                'nonchalant',
                'insouciant — casually unconcerned',
                'blasé',
              ],
            },
          ],
        },
        {
          kind: 'words',
          label: 'Group 9: abundance, scarcity, and size',
          clusters: [
            {
              items: [
                'prolific — producing much',
                'copious',
                'myriad',
                'plethora — an excess',
                'surfeit — an excess',
                'profusion',
                'teeming',
                'prodigious — impressively large',
                'inundate — flood',
              ],
            },
            {
              items: [
                'dearth — scarcity',
                'paucity — smallness of number',
                'exiguous — scanty',
                'meager',
                'sparse',
                'scant',
                'attenuate — make thin or weaken',
                'abate — lessen',
                'assuage — ease',
                'mitigate — make less severe',
                'ameliorate — make better',
                'curtail — cut short',
                'truncate',
              ],
            },
          ],
        },
        {
          kind: 'words',
          label: 'Group 10: new, old, and ordinary',
          clusters: [
            {
              items: [
                'novel',
                'innovative',
                'unprecedented',
                'nascent — just coming into existence',
                'incipient — in an early stage',
                'burgeoning — growing rapidly',
                'inchoate — not fully formed',
              ],
            },
            {
              items: [
                'archaic',
                'antiquated',
                'obsolete',
                'anachronistic — out of its proper time',
                'vestigial — a remnant',
              ],
            },
            {
              items: [
                'banal — unoriginal',
                'trite',
                'hackneyed — overused',
                'platitude — a trite remark',
                'prosaic — dull, ordinary',
                'pedestrian — uninspired',
                'mundane',
                'insipid — lacking flavor or interest',
                'vapid',
                'jejune — naive or dull',
                'derivative — unoriginal',
              ],
            },
          ],
        },
        {
          kind: 'words',
          label: 'Group 11: clarity, difficulty, and understanding',
          clusters: [
            {
              items: [
                'lucid — clear',
                'perspicuous — clearly expressed',
                'cogent — convincing',
                'salient — most noticeable',
                'explicit',
              ],
            },
            {
              items: [
                'abstruse — hard to understand',
                'recondite — obscure, known to few',
                'arcane — understood by few',
                'esoteric — for a select few',
                'opaque',
                'inscrutable — impossible to interpret',
                'enigmatic',
                'cryptic',
                'byzantine — excessively complicated',
                'labyrinthine',
              ],
            },
            {
              items: [
                'perspicacious — having keen insight',
                'astute',
                'sagacious — wise',
                'discerning',
                'erudite — learned',
                'pedantic — excessively concerned with rules or detail',
              ],
            },
          ],
        },
        {
          kind: 'words',
          label: 'Group 12: the rest, worth knowing',
          clusters: [
            {
              items: [
                'anomaly — a deviation',
                'antipathy — deep dislike',
                'ascetic — severely self-disciplined',
                'assiduous — diligent',
                'austere — severe or plain',
                'cacophony — harsh discord',
                'capricious — given to sudden changes',
                'catalyst',
                'chronicle',
                'cosmopolitan',
                'deference — respectful submission',
                'didactic — intended to teach, often moralizing',
                'disabuse — free from a misconception',
                'eclectic — drawn from varied sources',
                'egregious — outstandingly bad',
                'enervate — weaken',
                'ephemeral — short-lived',
                'equanimity — composure',
                'exacerbate — worsen',
                'exculpate — clear of guilt',
                'fastidious — attentive to detail, hard to please',
                'fervent — passionate',
                'fortuitous — happening by chance',
                'germane — relevant',
                'iconoclast — one who attacks cherished beliefs',
                'idiosyncratic — peculiar to an individual',
                'inimical — hostile, harmful',
                'innocuous — harmless',
                'intrepid — fearless',
                'lassitude — weariness',
                'maverick',
                'mercurial — volatile',
                'meticulous',
                'misanthrope — one who hates humankind',
                'obviate — make unnecessary',
                'ostentatious — showy',
                'paragon — a model of excellence',
                'partisan — biased toward a faction',
                'penchant — a strong liking',
                'penurious — extremely poor or stingy',
                'peripheral',
                'pervasive',
                'placate',
                'pragmatic',
                'precarious — unstable',
                'preclude — prevent',
                'propensity — an inclination',
                'quixotic — idealistic and impractical',
                'reclusive',
                'redolent — evocative of; fragrant',
                'relegate — assign to a lower position',
                'reprehensible — deserving censure',
                'rescind — revoke',
                'sanguine — optimistic',
                'soporific — sleep-inducing',
                'spurious — false',
                'squander',
                'sublime',
                'superfluous — unnecessary',
                'tenuous — weak, flimsy',
                'transient',
                'ubiquitous — everywhere',
                'venal — open to bribery',
                'vociferous — loudly insistent',
                'zealot',
              ],
            },
          ],
        },
      ],
    },
    {
      id: 'unknown-words',
      title: 'Working with words you do not know',
      blocks: [
        { kind: 'p', text: 'You will meet unknown words on test day. Three moves, in order:' },
        {
          kind: 'ol',
          items: [
            '**Charge from roots and sound.** *Malfeasance* is negative. *Beneficent* is positive. This alone eliminates choices.',
            '**Charge from where you have heard it.** If a word rings vaguely unpleasant, trust that. Your instinct about connotation is better than your recall of definitions.',
            '**Eliminate what you do know.** On Sentence Equivalence, if you know four words and can rule out three, the odds on the remaining pair improve sharply.',
          ],
        },
      ],
    },
  ],
};
